package utils

import (
	"spark/internal/models"

	"gorm.io/gorm"
)

// CalculateNewDriverRating recalculates and updates a driver's average rating.
// It fetches all ratings for the driver, calculates the average, and updates the driver record.
func CalculateNewDriverRating(db *gorm.DB, driverID uint) error {
	var ratings []models.Rating
	// Find all ratings where the driver is the rated entity
	if err := db.Where("rated_id = ?", driverID).Find(&ratings).Error; err != nil {
		return err
	}

	if len(ratings) == 0 {
		return nil // No ratings yet, nothing to calculate
	}

	var totalRating int
	for _, r := range ratings {
		totalRating += r.Rating
	}

	averageRating := float64(totalRating) / float64(len(ratings))

	// Update the driver's average rating in the database
	// Using "average_rating" to match the database column name typically generated by GORM
	if err := db.Model(&models.Driver{}).Where("id = ?", driverID).Update("average_rating", averageRating).Error; err != nil {
		return err
	}

	return nil
}
